extraction:
  cpp:
    configure:
      command:
      - "./configure --disable-tests --disable-doc --disable-gtk-doc --disable-dependency-tracking"
    index:
      build_command:
      - "make -j4"
